# Generated by Django 4.2.2 on 2025-06-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("send", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["client"],
                "permissions": [
                    ("can_edit_email", "Can edit can_edit_email"),
                    ("can_edit_name", "Can edit name"),
                    ("can_edit_comment", "Can edit comment"),
                ],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["message"],
                "permissions": [
                    ("can_edit_subject_letter", "Can edit subject_letter"),
                    ("can_edit_letter", "Can edit letter"),
                ],
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
            },
        ),
    ]
