# Generated by Django 4.2.2 on 2025-07-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("send", "0002_alter_client_options_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["client"],
                "permissions": [
                    ("can_edit_email", "Can edit can edit email"),
                    ("can_edit_name", "Can edit name"),
                    ("can_edit_comment", "Can edit comment"),
                ],
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID Клиента",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID Сообщения клиента",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите автора письма",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="send.client",
                verbose_name="Владелец",
            ),
        ),
    ]
