# Generated by Django 4.2.2 on 2025-07-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("send", "0005_newsletter_owner_alter_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["disabling_mailings"],
                "permissions": [
                    ("can_edit_disabling_mailings", "Сan edit disabling mailings")
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
