# Generated by Django 4.2.2 on 2025-07-03 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("send", "0006_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailattempt",
            options={"verbose_name": "попытка", "verbose_name_plural": "попытки"},
        ),
        migrations.AddField(
            model_name="mailattempt",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mail_attempts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Введите комментарий о клиенте",
                max_length=1000,
                null=True,
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Email Клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Введите инициалы клиента",
                max_length=150,
                null=True,
                verbose_name="Ф.И.О.",
            ),
        ),
        migrations.AlterField(
            model_name="mailattempt",
            name="date_attempt",
            field=models.DateTimeField(auto_now=True, verbose_name="Время попытки"),
        ),
        migrations.AlterField(
            model_name="mailattempt",
            name="newsletter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletter",
                to="send.newsletter",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="mailattempt",
            name="status_mailing_attempt",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                max_length=50,
                verbose_name="Статус попытки",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="letter",
            field=models.TextField(
                blank=True,
                help_text="Введите текст",
                max_length=300,
                null=True,
                verbose_name="Текст сообщения",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject_letter",
            field=models.CharField(
                blank=True,
                help_text="Введите тему",
                max_length=100,
                null=True,
                verbose_name="Тема сообщения",
            ),
        ),
    ]
