# Generated by Django 4.2.2 on 2025-07-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("send", "0007_alter_mailattempt_options_mailattempt_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="end_shipment",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                max_length=10,
                null=True,
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="first_shipment",
            field=models.DateTimeField(
                auto_now_add=True,
                max_length=10,
                null=True,
                verbose_name="Дата и время первой отправки",
            ),
        ),
    ]
